### ISSUE TITLE
 Design visual para a página da lista de produtos

### ISSUE THREAD

**Issue by pedro-v-bezerra** [Gabriel-neto/Black_box_mobile#41]

**Comment by pedro-v-bezerra** [comment]
![Image](https://github.com/Gabriel-neto/Black_box_mobile/assets/62081545/d8ff4d4c-4f0c-4b75-8c7b-6e6b91845f44)

**Comment by iamedusm** [comment]
https://www.figma.com/proto/0cCeuQutivpIaW0C3X8AFT/PI-FRONT-END?type=design&node-id=560-227&t=697AminDGYRDtztv-0&scaling=scale-down&page-id=1%3A8&starting-point-node-id=560%3A31
